### ISSUE TITLE
Duplicate Folder Icons

### ISSUE THREAD

**Issue by r-clancy** [alperenelhan/sublime-numix-theme#3]
When viewing directories in the sidebar, there are duplicate icons.

![dup](https://cloud.githubusercontent.com/assets/1282383/6487342/02b54f02-c267-11e4-898e-37237e288d13.PNG)

**Comment by grziwok** [comment]
There actually was a commit with fix for that issue, it seems like version on Package Control is outdated.

**Comment by si-robertson** [comment]
I don't suppose anyone knows what needs to be tweaked in the package to fix this? I have poked the `Numix.sublime-theme` file with a stick a few times but haven't been able to fix this weird icon issue yet.

**Comment by tcoulter** [comment]
@si-robertson Can you tell me how you did that? Is that file a zip file, for instance? I've found the file but not sure where to go from there.

**Comment by tcoulter** [comment]
**Edit**: Ignore *me*. You can add the repository URL specifically via "Package Control: Add Repository", and then install it as normal. This will override the previous version, fixing the issue.

For reference, the URL I added was `https://github.com/alperenelhan/sublime-numix-theme`

**Comment by si-robertson** [comment]
@tcoulter Good to know you found a (better) solution. Installing directly from this repository would have saved me some time.

For reference, `sublime-package` files are in fact `zip` files. You can access/update everything in a bundled package by swapping the file extension when needed.
